Repository toy-1/wiki, pull requests merged in 2023-09, with the labels that each got.

#13 위키 페이지 레이아웃 작성 및 기본 기능 구현
  src/components/wiki/WikiButton.tsx
  src/components/wiki/WikiButtonStyle.ts
  src/components/wiki/WikiCategoryList.tsx
  src/components/wiki/WikiCategoryListStyle.ts
  src/components/wiki/WikiContent.tsx
  src/components/wiki/WikiContentStyle.ts
  src/components/wiki/WikiForm.tsx
  src/components/wiki/WikiFormStyle.ts
  src/components/wiki/WikiTop.tsx
  src/components/wiki/WikiTopStyle.ts
  src/db/wiki/wikiInitData.json
  src/pages/wiki/Wiki.tsx
  src/pages/wiki/WikiStyle.ts
  src/pages/wiki/wikiStyle.ts
  src/styles/globalStyle.ts
Labels: feat

#12 [Login] 레이아웃 구성 및 로그인/ 회원가입(모달) 기능 추가
  src/components/login/SignIn.tsx
  src/components/login/SignUp.tsx
  src/components/login/signinStyle.ts
  src/components/login/signupStyle.ts
  src/pages/login/Login.tsx
  src/pages/login/context/authContext.tsx
  src/pages/login/context/authProvider.tsx
  src/pages/login/loginStyle.ts
Labels: feat

#10 사이드바 설정 기능 및 전체적인 갤러리 페이지 레이아웃
  firebase.ts
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/common/InputStyle.ts
  src/components/common/buttonStyle.ts
  src/components/gallery/AddList.tsx
  src/components/gallery/AddListStyle.tsx
  src/components/gallery/GalleryHeader.tsx
  src/components/gallery/GalleryHeaderStyle.ts
  src/components/gallery/GalleryMain.tsx
  src/components/gallery/GalleryMainStyle.ts
  src/components/gallery/GallerySide.tsx
  src/components/gallery/GallerySideStyle.ts
  src/pages/gallery/Gallery.tsx
  src/pages/gallery/galleryStyle.ts
  src/styles/globalStyle.ts
Labels: feat

#24 로그인 여부에 따른 페이지 라우팅 기능, 로그인 유저 ID값 전달 기능 구현
  src/App.tsx
  src/AppRouter.tsx
  src/components/common/RootPage.tsx
  src/components/login/SignIn.tsx
  src/components/login/SignUp.tsx
  src/components/login/signupStyle.ts
  src/pages/login/Login.tsx
Labels: feat

#26 갤러리 페이지 이미지 상세보기 및 기능 추가 및 카테고리바 디자인 수정
  src/components/gallery/CurrentImg.tsx
  src/components/gallery/CurrentImgStyle.tsx
  src/components/gallery/GalleryHeaderStyle.ts
  src/components/gallery/GalleryMain.tsx
  src/components/gallery/GalleryMainStyle.ts
  src/components/gallery/GallerySide.tsx
  src/components/gallery/GallerySideStyle.ts
  src/pages/gallery/Gallery.tsx
  src/pages/gallery/galleryStyle.ts
Labels: feat

#30 Feat 위키 페이지 마크다운 에디터 적용 등 기능 추가
  package-lock.json
  package.json
  src/components/wiki/WikiCategoryList.tsx
  src/components/wiki/WikiCategoryListStyle.ts
  src/components/wiki/WikiContent.tsx
  src/components/wiki/WikiContentStyle.ts
  src/components/wiki/WikiForm.tsx
  src/components/wiki/WikiFormStyle.ts
  src/db/wiki/wikiInitData.json
  src/pages/wiki/Wiki.tsx
  src/pages/wiki/WikiType.ts
Labels: feat

#32 이미지 업로드 및 삭제 기능 추가
  public/images/upload-image.png
  src/components/gallery/AddImg.tsx
  src/components/gallery/AddImgStyle.tsx
  src/components/gallery/CurrentImg.tsx
  src/components/gallery/CurrentImgStyle.tsx
  src/components/gallery/GalleryMain.tsx
  src/components/gallery/GalleryMainStyle.ts
  src/components/gallery/GallerySide.tsx
  src/pages/gallery/Gallery.tsx
Labels: feat

#34 갤러리 카테고리바 디자인 수정 및 이미지 변경 버그 수정 (최종 완성본)
  src/components/common/Input.tsx
  src/components/common/InputStyle.ts
  src/components/gallery/AddImg.tsx
  src/components/gallery/AddImgStyle.tsx
  src/components/gallery/CurrentImg.tsx
  src/components/gallery/GalleryHeaderStyle.ts
  src/components/gallery/GallerySide.tsx
  src/components/gallery/GallerySideStyle.ts
Labels: feat

#43 리드미 업데이트 입니다.
  README.md
Labels: feat

#54 갤러리 페이지 모달 z-index 문제 해결 및 이미지 삭제 버튼 디자인 수정
  README.md
  src/components/common/Input.tsx
  src/components/common/InputStyle.ts
  src/components/gallery/AddImgStyle.tsx
  src/components/gallery/AddListStyle.tsx
  src/components/gallery/CurrentImgStyle.tsx
Labels: bug

#60 리드미 업데이트
  README.md
Labels: Docs

#57 Feat: 위키 쿼리스트링 받아 오는 로직 추가 등 기능 추가
  src/components/wiki/RenderWikiContent.tsx
  src/components/wiki/RenderWikiForm.tsx
  src/components/wiki/WikiButton.tsx
  src/components/wiki/WikiButtonStyle.ts
  src/components/wiki/WikiCommonType.ts
  src/components/wiki/WikiContent.tsx
  src/components/wiki/WikiContentStyle.ts
  src/pages/wiki/Wiki.tsx
Labels: feat

#62 Fix: 페이지 진입 시 처음 선택된 위키의 부모 위키 변경 기능의 버그 수정
  src/components/wiki/RenderWikiForm.tsx
  src/components/wiki/WikiCommonType.ts
  src/components/wiki/WikiContent.tsx
  src/pages/wiki/Wiki.tsx
Labels: bug

#64 타입 오류 해결
  src/components/home/Carousel.tsx
  src/components/home/GalleryPreview.tsx
  src/pages/gallery/Gallery.tsx
  src/pages/login/context/authProvider.tsx
Labels: bug

#76 Fix Bug/#63
  src/components/wiki/RenderWikiContent.tsx
  src/components/wiki/RenderWikiForm.tsx
  src/components/wiki/RenderWikiFormStyle.ts
  src/components/wiki/WikiCategoryList.tsx
  src/components/wiki/WikiCategoryListStyle.ts
  src/components/wiki/WikiTopStyle.ts
  src/pages/wiki/Wiki.tsx
Labels: bug

#79 Feat: favicon 추가
  index.html
  public/icon/favicon-16x16.png
Labels: feat

#93 배포 오류 슈정
  package-lock.json
  package.json
  public/images/github-logo.png
  src/AppRouter.tsx
  src/components/common/Fooder.tsx
  src/components/common/FooterStyle.ts
  tsconfig.json
Labels: bug

#94 Fix: 위키 사이드 메뉴에서 자식 위키가 없는 부모 위키는 전개 버튼을 감추도록 변경
  src/components/wiki/RenderWikiForm.tsx
  src/components/wiki/WikiCategoryList.tsx
  src/components/wiki/WikiCommonType.ts
  src/components/wiki/WikiContent.tsx
  src/firebase/services/wikiService.ts
  src/pages/wiki/Wiki.tsx
Labels: bug, feat

#91 Style: 네비게이션 메뉴 스타일 변경
  src/components/common/headerStyle.ts
Labels: feat

#104 Refactor: firebase.ts 이동 및 관련 경로 수정
  src/App.tsx
  src/components/common/CommuteModal.tsx
  src/components/common/Header.tsx
  src/components/common/RootPage.tsx
  src/components/gallery/AddImg.tsx
  src/components/gallery/AddList.tsx
  src/components/gallery/CurrentImg.tsx
  src/components/gallery/GallerySide.tsx
  src/components/home/GalleryPreview.tsx
  src/components/home/WikiPreview.tsx
  src/components/login/SignIn.tsx
  src/components/login/SignUp.tsx
  src/firebase/firebase.ts
  src/firebase/services/wikiService.ts
  src/pages/gallery/Gallery.tsx
  src/pages/home/Home.tsx
  src/pages/login/context/authProvider.tsx
  src/pages/wiki/Wiki.tsx
Labels: refactor

#110 갤러리페이지 사이드바 버튼 텍스트 수정
  src/components/gallery/GallerySide.tsx
Labels: feat

#103 아이콘 오류 수정중...(머지X)
  package-lock.json
  package.json
  src/components/gallery/GallerySide.tsx
  src/components/wiki/WikiCategoryList.tsx
Labels: bug

#111 갤러리 사이드바 타입 수정 Boolean -> boolean
  src/components/gallery/GallerySide.tsx
Labels: refactor

#118 Feat: 로그인페이지 푸터 미노출 기능 추가
  src/components/common/Footer.tsx
Labels: feat

#117 Refactor/#100
  package-lock.json
  package.json
  src/components/home/WikiPreview.tsx
  src/components/wiki/WikiCategoryList.tsx
  src/components/wiki/buttons/WikiButton.tsx
  src/components/wiki/buttons/WikiButtonStyle.ts
  src/components/wiki/category/ChildWikiItem.tsx
  src/components/wiki/category/ParentWikiItem.tsx
  src/components/wiki/category/WikiCategoryList.tsx
  src/components/wiki/category/WikiCategoryListItem.tsx
  src/components/wiki/category/WikiCategoryListStyle.ts
  src/components/wiki/content/RenderNoWiki.tsx
  src/components/wiki/content/RenderWikiContent.tsx
  src/components/wiki/content/RenderWikiForm.tsx
  src/components/wiki/content/RenderWikiFormStyle.ts
  src/components/wiki/content/WikiContent.tsx
  src/components/wiki/content/WikiContentStyle.ts
  src/components/wiki/markdown/MarkdownEditor.tsx
  src/components/wiki/markdown/MarkdownViewer.tsx
  src/components/wiki/top/WikiTop.tsx
  src/components/wiki/top/WikiTopStyle.ts
  src/components/wiki/types/WikiCommonType.ts
  src/firebase/services/wikiService.ts
  src/pages/home/Home.tsx
  src/pages/wiki/Wiki.tsx
Labels: refactor

#125 갤러리 이미지 전환 배열 오류 수정
  src/components/gallery/CurrentImg.tsx
  src/components/gallery/GallerySide.tsx
Labels: bug

#121 dev -> main (머지X)
  README.md
  package-lock.json
  package.json
  src/components/common/Footer.tsx
  src/components/common/FooterStyle.ts
  src/components/gallery/CurrentImg.tsx
  src/components/gallery/GallerySide.tsx
  src/components/home/Carousel.tsx
  src/components/home/CarouselStyle.ts
  src/components/home/WikiPreview.tsx
  src/components/wiki/WikiCategoryList.tsx
  src/components/wiki/buttons/WikiButton.tsx
  src/components/wiki/buttons/WikiButtonStyle.ts
  src/components/wiki/category/ChildWikiItem.tsx
  src/components/wiki/category/ParentWikiItem.tsx
  src/components/wiki/category/WikiCategoryList.tsx
  src/components/wiki/category/WikiCategoryListItem.tsx
  src/components/wiki/category/WikiCategoryListStyle.ts
  src/components/wiki/content/RenderNoWiki.tsx
  src/components/wiki/content/RenderWikiContent.tsx
  src/components/wiki/content/RenderWikiForm.tsx
  src/components/wiki/content/RenderWikiFormStyle.ts
  src/components/wiki/content/WikiContent.tsx
  src/components/wiki/content/WikiContentStyle.ts
  src/components/wiki/markdown/MarkdownEditor.tsx
  src/components/wiki/markdown/MarkdownViewer.tsx
  src/components/wiki/top/WikiTop.tsx
  src/components/wiki/top/WikiTopStyle.ts
  src/components/wiki/types/WikiCommonType.ts
  src/firebase/services/wikiService.ts
  src/pages/home/Home.tsx
  src/pages/home/homeStyle.ts
  src/pages/wiki/Wiki.tsx
Labels: 완성!

#126 Docs/#122 위키페이지 리드미 작성
  README.md
Labels: Docs

#128 최종 완료 q(≧▽≦q)
  README.md
Labels: 완성!
